// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMBlzFAirLpR3cAf0FxuqkYgl_sASWSIU',
    appId: '1:29060236527:web:01a7445fe92c30b31fc71a',
    messagingSenderId: '29060236527',
    projectId: 'future-aa9f1',
    authDomain: 'future-aa9f1.firebaseapp.com',
    storageBucket: 'future-aa9f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ebGNo79qsQV6i8MH64R9CQF5o7sGZSk',
    appId: '1:29060236527:android:fe1d73cb600cf4251fc71a',
    messagingSenderId: '29060236527',
    projectId: 'future-aa9f1',
    storageBucket: 'future-aa9f1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMBlzFAirLpR3cAf0FxuqkYgl_sASWSIU',
    appId: '1:29060236527:web:aaabc21d61ac7cb81fc71a',
    messagingSenderId: '29060236527',
    projectId: 'future-aa9f1',
    authDomain: 'future-aa9f1.firebaseapp.com',
    storageBucket: 'future-aa9f1.appspot.com',
  );
}
